# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2531d8a583246682dd927e41bbb0ac8add45f7c6538b8b9fa21a19d621567e99666abdad1b0d48435cb5d17d155973980c19a6331209d6d31bdaf654d10b16d2

test:
  secret_key_base: dfe521d59e15295bb78ed86ca70db0e6b2d764191663a151004e6772ac3a082d2c8c2a93df5f91c4fc3b7c0a459c68e60a2696c51e3a4fe15f7c7f561feaf335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
